spring:
  application:
    name: ClassTrack-SpringBoot-RestAPI
#Datasource Configuration
  datasource:
    url: jdbc:h2:mem:classtrack
    username: sa
    password:
    driver-class-name: org.h2.Driver
# jpa Configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
# H2 Configuration
  h2:
    console:
      enabled: true
      path: /h2-console

  boot:
    admin:
      client:
        url: http://localhost:8081

#  security:
#    user: { name: dev, password: dev, roles: ADMIN }

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  file:
    name: logs/application.log
  logback:
    rollingpolicy:
      max-history: 20
      total-size-cap: 20MB

#Swagger Configuration
#API Documentation Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger

